-- Top paid employees ranked within each department
with ranked_emp as ( 
select  e.employees_id,CONCAT(e.first_name, ' ', e.last_name) as employee_name,
e.job_title,e.departments_id,d.name,e.salary,dense_rank() over (partition by e.departments_id order by  e.salary desc) as rank_in_dept
from employees e
join departments d on e.departments_id=d.departments_id
 )
SELECT *
FROM ranked_emp
WHERE rank_in_dept <= 3
ORDER BY departments_id, rank_in_dept;




-- Revenue generated by each employee (min 1 sale)
select e.employees_id,concat(e.first_name," ",e.last_name) as Employee_Name,
count(s.Sales_id) as Total_Sales,sum(s.total_price) as Total_Revenue,Round(avg(s.total_price),2)Avg_Order_Value,
rank() over(ORDER BY SUM(s.total_price) DESC) AS revenue_rank
from employees e
join sales s on e.Employees_id=s.Employees_id
group by e.employees_id,e.first_name,e.last_name
order by  revenue_rank ;




-- Top 3 best-selling products in each category
with product_sales as (select p.Products_id,p.Name as product_name,c.Name as category_name,sum(ps.Quantity)as total_quantity_sold,
count(ps.Sales_id) as total_orders,dense_rank() over (PARTITION BY p.Categories_id ORDER BY SUM(ps.Quantity) DESC) as rank_in_category
from Products p
join Pro_Sales ps on p.Products_id = ps.Products_id
join Categories c on p.Categories_id = c.Categories_id
group by  p.Products_id, p.Name, c.Name, p.Categories_id
)
SELECT *
FROM product_sales
WHERE rank_in_category <= 3
ORDER BY category_name, rank_in_category;



-- Customers who registered but never placed an order
select c.Customers_id,concat(c.first_name," ",c.last_name) as customer_name,p.phone_number,p.email
from customers c
join parties p on p.parties_id=c.parties_id
left join sales s on s.Customers_id=c.Customers_id
where sales_id is null; 



-- Total maintenance cost broken down by product category
with MaintCost as (select mi.Stock_id,sum(m.Total_Reparing_price) as Total_Cost,count(m.Maintenance_id) as Repairs_Count
from Maintenance m
join Maintenance_item mi on m.Maintenance_Item_id = mi.Maintenance_Item_id
group by mi.Stock_id
),
StockProducts as (select sp.Stock_id, p.Categories_id, count(*) as Product_Count
from Stock_Products sp
join Products p on sp.Products_id = p.Products_id
group by sp.Stock_id, p.Categories_id
)
SELECT c.Name as Category,sum(mc.Total_Cost) as Total_Maintenance_Cost,sum(mc.Repairs_Count) as Total_Repairs,
sum(sp.Product_Count) AS Products_in_Stock
from MaintCost mc
join StockProducts sp on mc.Stock_id    = sp.Stock_id
join Categories c on sp.Categories_id = c.Categories_id
group by c.Name
order by  Total_Maintenance_Cost DESC;


-- Customer segmentation based on total spend
SELECT c.customers_id,CONCAT(c.first_name, ' ', c.last_name) AS customer_name,COUNT(s.sales_id) AS total_orders,SUM(s.total_price) AS total_spent,
    CASE
        WHEN SUM(s.total_price) >= 50000 THEN 'VIP'
        WHEN SUM(s.total_price) >= 10000 THEN 'Regular'
        WHEN SUM(s.total_price) IS NULL THEN 'No Purchases'
        ELSE 'New / Low Value'
    END AS customer_segment
FROM customers c
LEFT JOIN sales s ON s.customers_id = c.customers_id
GROUP BY c.customers_id, c.first_name, c.last_name
ORDER BY total_spent DESC;







